import type {
  Age,
  BuildingDefinition,
  BuildingType,
  ResourceBag,
  ResearchId,
  TechTreeNode,
  UnitDefinition,
  UnitType,
} from "./types";

function cost(food = 0, timber = 0, stone = 0, iron = 0): Partial<ResourceBag> {
  return { food, timber, stone, iron };
}

export const AGE_ORDER: Age[] = ["settlement", "abbey", "warhost"];

export const UNIT_DEFINITIONS: Record<UnitType, UnitDefinition> = {
  worker: {
    id: "worker",
    label: "Worker",
    description: "Economic unit for gathering, hauling, and constructing the frontier camp.",
    weaponLabel: "Mallet & Hatchet",
    producedAt: "abbeyHall",
    age: "settlement",
    cost: cost(50),
    trainTimeMs: 3500,
    hp: 55,
    speed: 1.4,
    sight: 5,
    attackDamage: 4,
    attackRange: 1.1,
    attackCooldownMs: 1400,
    gatherRate: { food: 10, timber: 8, stone: 6, iron: 5 },
    carryCapacity: 30,
    armor: 0,
    species: "mouse",
    tags: ["worker"],
  },
  shrewScout: {
    id: "shrewScout",
    label: "Shrew Scout",
    description: "Fast reconnaissance runner with wide sight for scouting routes and incoming pressure.",
    weaponLabel: "Scout Spear",
    producedAt: "abbeyHall",
    age: "settlement",
    cost: cost(60, 20),
    trainTimeMs: 3200,
    hp: 70,
    speed: 2.15,
    sight: 8,
    attackDamage: 5,
    attackRange: 1.2,
    attackCooldownMs: 1200,
    armor: 0,
    species: "shrew",
    tags: ["scout"],
  },
  militia: {
    id: "militia",
    label: "Militia",
    description: "Basic melee line-holder for the first fights around your economy.",
    weaponLabel: "Oak Staff",
    producedAt: "barracks",
    age: "settlement",
    cost: cost(55, 20),
    trainTimeMs: 4200,
    hp: 95,
    speed: 1.35,
    sight: 5,
    attackDamage: 10,
    attackRange: 1.2,
    attackCooldownMs: 1200,
    armor: 1,
    species: "mouse",
    tags: ["infantry"],
  },
  shieldbearer: {
    id: "shieldbearer",
    label: "Shieldbearer",
    description: "Durable infantry that absorbs punishment and anchors the front line.",
    weaponLabel: "Spear & Kite Shield",
    producedAt: "barracks",
    age: "abbey",
    cost: cost(70, 25, 10),
    trainTimeMs: 5600,
    hp: 140,
    speed: 1.15,
    sight: 5,
    attackDamage: 13,
    attackRange: 1.1,
    attackCooldownMs: 1200,
    armor: 3,
    species: "mouse",
    tags: ["infantry"],
  },
  slinger: {
    id: "slinger",
    label: "Slinger",
    description: "Low-cost ranged support for early volleys and skirmishes.",
    weaponLabel: "Leather Sling",
    producedAt: "range",
    age: "abbey",
    cost: cost(40, 35),
    trainTimeMs: 4000,
    hp: 70,
    speed: 1.35,
    sight: 6,
    attackDamage: 9,
    attackRange: 4.2,
    attackCooldownMs: 1300,
    armor: 0,
    species: "mouse",
    tags: ["ranged"],
  },
  archer: {
    id: "archer",
    label: "Archer",
    description: "Longer-range ranged unit for focused pressure and defense.",
    weaponLabel: "Yew Bow",
    producedAt: "range",
    age: "abbey",
    cost: cost(45, 45),
    trainTimeMs: 4800,
    hp: 78,
    speed: 1.3,
    sight: 6,
    attackDamage: 12,
    attackRange: 4.8,
    attackCooldownMs: 1500,
    armor: 0,
    species: "mouse",
    tags: ["ranged"],
  },
  otterSkirmisher: {
    id: "otterSkirmisher",
    label: "Otter Skirmisher",
    description: "Mobile warhost ranged unit with a stronger combat profile than early archers.",
    weaponLabel: "Javelins",
    producedAt: "range",
    age: "warhost",
    cost: cost(65, 30, 15),
    trainTimeMs: 5200,
    hp: 90,
    speed: 1.55,
    sight: 6,
    attackDamage: 13,
    attackRange: 4.4,
    attackCooldownMs: 1200,
    armor: 1,
    species: "otter",
    tags: ["ranged"],
  },
  hareRunner: {
    id: "hareRunner",
    label: "Hare Runner",
    description: "Fast striking infantry for raids, flanks, and quick reinforcement.",
    weaponLabel: "Sabre Pair",
    producedAt: "longPatrolLodge",
    age: "warhost",
    cost: cost(75, 35, 20),
    trainTimeMs: 5200,
    hp: 110,
    speed: 1.95,
    sight: 7,
    attackDamage: 14,
    attackRange: 1.2,
    attackCooldownMs: 1000,
    armor: 1,
    species: "hare",
    tags: ["infantry", "scout"],
  },
  badgerChampion: {
    id: "badgerChampion",
    label: "Badger Champion",
    description: "Heavy elite bruiser meant to smash through late-game positions.",
    weaponLabel: "War Mattock",
    producedAt: "longPatrolLodge",
    age: "warhost",
    cost: cost(115, 25, 35, 20),
    trainTimeMs: 7600,
    hp: 220,
    speed: 1.25,
    sight: 6,
    attackDamage: 24,
    attackRange: 1.3,
    attackCooldownMs: 1000,
    armor: 4,
    species: "badger",
    tags: ["infantry", "heroic"],
  },
  ramCart: {
    id: "ramCart",
    label: "Ram Cart",
    description: "Siege engine for bringing down towers, halls, and fortified lines.",
    weaponLabel: "Bound Log Ram",
    producedAt: "workshop",
    age: "warhost",
    cost: cost(50, 85, 70),
    trainTimeMs: 7000,
    hp: 180,
    speed: 0.95,
    sight: 5,
    attackDamage: 34,
    attackRange: 1.1,
    attackCooldownMs: 1800,
    armor: 5,
    species: "machine",
    tags: ["siege"],
  },
};

export const BUILDING_DEFINITIONS: Record<BuildingType, BuildingDefinition> = {
  abbeyHall: {
    id: "abbeyHall",
    label: "Abbey Hall",
    age: "settlement",
    cost: cost(0),
    buildTimeMs: 0,
    hp: 850,
    footprint: { x: 2, y: 2 },
    sight: 8,
    production: ["worker", "shrewScout", "abbey", "warhost"],
    resourceDropoff: ["food", "timber", "stone", "iron"],
    populationCap: 8,
  },
  dormitory: {
    id: "dormitory",
    label: "Dormitory",
    age: "settlement",
    cost: cost(0, 65),
    buildTimeMs: 3500,
    hp: 180,
    footprint: { x: 1, y: 1 },
    sight: 4,
    populationCap: 8,
  },
  storehouse: {
    id: "storehouse",
    label: "Storehouse",
    age: "settlement",
    cost: cost(0, 70),
    buildTimeMs: 4200,
    hp: 220,
    footprint: { x: 1, y: 1 },
    sight: 5,
    resourceDropoff: ["timber", "stone", "iron"],
  },
  granary: {
    id: "granary",
    label: "Granary",
    age: "settlement",
    cost: cost(50, 55),
    buildTimeMs: 4200,
    hp: 220,
    footprint: { x: 1, y: 1 },
    sight: 5,
    production: ["woodcraft"],
    resourceDropoff: ["food"],
  },
  barracks: {
    id: "barracks",
    label: "Barracks",
    age: "settlement",
    cost: cost(0, 95),
    buildTimeMs: 5000,
    hp: 260,
    footprint: { x: 2, y: 1 },
    sight: 5,
    production: ["militia", "shieldbearer"],
  },
  range: {
    id: "range",
    label: "Range",
    age: "abbey",
    cost: cost(0, 105),
    buildTimeMs: 5400,
    hp: 250,
    footprint: { x: 2, y: 1 },
    sight: 5,
    production: ["slinger", "archer", "otterSkirmisher"],
  },
  blacksmith: {
    id: "blacksmith",
    label: "Blacksmith",
    age: "abbey",
    cost: cost(0, 85, 20),
    buildTimeMs: 5000,
    hp: 240,
    footprint: { x: 1, y: 1 },
    sight: 5,
    production: ["stoneMasonry", "ironforging", "leatherwork", "towerGuard", "hareDrills"],
  },
  longPatrolLodge: {
    id: "longPatrolLodge",
    label: "Long Patrol Lodge",
    age: "warhost",
    cost: cost(90, 85, 25),
    buildTimeMs: 5800,
    hp: 280,
    footprint: { x: 2, y: 1 },
    sight: 6,
    production: ["hareRunner", "badgerChampion"],
  },
  tower: {
    id: "tower",
    label: "Tower",
    age: "abbey",
    cost: cost(0, 40, 80),
    buildTimeMs: 4800,
    hp: 320,
    footprint: { x: 1, y: 1 },
    sight: 7,
    attackDamage: 14,
    attackRange: 5.5,
    attackCooldownMs: 1300,
  },
  wall: {
    id: "wall",
    label: "Wall",
    age: "abbey",
    cost: cost(0, 0, 18),
    buildTimeMs: 1400,
    hp: 180,
    footprint: { x: 1, y: 1 },
    sight: 3,
  },
  gate: {
    id: "gate",
    label: "Gate",
    age: "abbey",
    cost: cost(0, 0, 28),
    buildTimeMs: 1800,
    hp: 230,
    footprint: { x: 1, y: 1 },
    sight: 3,
    passable: true,
  },
  workshop: {
    id: "workshop",
    label: "Workshop",
    age: "warhost",
    cost: cost(0, 120, 50, 20),
    buildTimeMs: 6200,
    hp: 280,
    footprint: { x: 2, y: 1 },
    sight: 5,
    production: ["ramCart"],
  },
};

export const RESEARCH_DEFINITIONS: Record<ResearchId, TechTreeNode> = {
  abbeyAge: {
    id: "abbeyAge",
    label: "Advance to Abbey Age",
    age: "settlement",
    buildingType: "abbeyHall",
    cost: cost(180, 120),
    researchTimeMs: 9000,
    grants: ["Unlock Range, Blacksmith, Tower and stronger troops"],
  },
  warhostAge: {
    id: "warhostAge",
    label: "Advance to Warhost Age",
    age: "abbey",
    buildingType: "abbeyHall",
    cost: cost(260, 180, 120, 60),
    researchTimeMs: 12000,
    grants: ["Unlock elite units and workshop"],
  },
  woodcraft: {
    id: "woodcraft",
    label: "Woodcraft",
    age: "settlement",
    buildingType: "granary",
    cost: cost(60, 40),
    researchTimeMs: 5000,
    grants: ["Worker gather rate +15%"],
  },
  stoneMasonry: {
    id: "stoneMasonry",
    label: "Stone Masonry",
    age: "abbey",
    buildingType: "blacksmith",
    cost: cost(0, 40, 70),
    researchTimeMs: 5500,
    grants: ["Buildings +20% health"],
  },
  ironforging: {
    id: "ironforging",
    label: "Iron Forging",
    age: "abbey",
    buildingType: "blacksmith",
    cost: cost(0, 35, 0, 65),
    researchTimeMs: 5200,
    grants: ["Infantry and archers +2 damage"],
  },
  leatherwork: {
    id: "leatherwork",
    label: "Leatherwork",
    age: "abbey",
    buildingType: "blacksmith",
    cost: cost(0, 40, 30, 40),
    researchTimeMs: 5200,
    grants: ["Infantry and ranged units +1 armor"],
  },
  towerGuard: {
    id: "towerGuard",
    label: "Tower Guard",
    age: "warhost",
    buildingType: "blacksmith",
    cost: cost(0, 55, 70, 20),
    researchTimeMs: 6000,
    grants: ["Towers +5 damage"],
  },
  hareDrills: {
    id: "hareDrills",
    label: "Hare Drills",
    age: "warhost",
    buildingType: "blacksmith",
    cost: cost(85, 45, 0, 40),
    researchTimeMs: 6000,
    grants: ["Hares move and attack faster"],
  },
};

export function getAgeIndex(age: Age): number {
  return AGE_ORDER.indexOf(age);
}

export function isAgeUnlocked(playerAge: Age, requiredAge: Age): boolean {
  return getAgeIndex(playerAge) >= getAgeIndex(requiredAge);
}
